### signup

POST http://localhost:5000/user/signup
Content-Type: application/json

{
  "name": "mohammad nowresideh",
  "email": "mohammad.nowresideh@gmail.com",
  "password": "123!@#Ss"
}

### login

POST http://localhost:5000/user/login
Content-Type: application/json

{
  "email": "mohammad.ha9bi8@gmail.com",
  "password": "123!@#Ss"
}

### create pants

POST http://localhost:5000/pants/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMDQ1NywiZXhwIjoxNjQyMjI0MDU3fQ.Xo0Lf4YzN2gCQmdgE3hKU1iEPV2NHD266SEnzX0VLic

{
  "name": "vahid",
  "height": 220,
  "waist": 123,
  "seat": 145,
  "thight": 12,
  "knee": 64,
  "pantSlipper": 77,
  "hip": 23,
  "phone": "09174163042"
}

### edit pants

PATCH http://localhost:5000/pants/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMDQ1NywiZXhwIjoxNjQyMjI0MDU3fQ.Xo0Lf4YzN2gCQmdgE3hKU1iEPV2NHD266SEnzX0VLic

{
  "id": 1,
  "name": "ali nowresideh",
  "height": 220,
  "waist": 123,
  "seat": 145,
  "thight": 12,
  "knee": 64,
  "pantSlipper": 77,
  "hip": 23,
  "phone": "09174163042"
}

### list of pants

GET http://localhost:5000/pants/list?page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMDQ1NywiZXhwIjoxNjQyMjI0MDU3fQ.Xo0Lf4YzN2gCQmdgE3hKU1iEPV2NHD266SEnzX0VLic

### get details

GET http://localhost:5000/pants/details?id=12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMDQ1NywiZXhwIjoxNjQyMjI0MDU3fQ.Xo0Lf4YzN2gCQmdgE3hKU1iEPV2NHD266SEnzX0VLic

### create shirt

POST http://localhost:5000/shirt/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMDQ1NywiZXhwIjoxNjQyMjI0MDU3fQ.Xo0Lf4YzN2gCQmdgE3hKU1iEPV2NHD266SEnzX0VLic

{
  "name": "vahid",
  "height": 220,
  "shoulder": 123,
  "sleeve": 145,
  "sleeveRing": 12,
  "armpit": 64,
  "chest": 77,
  "collar": 23,
  "phone": "09174163042"
}

### edit shirt

PATCH http://localhost:5000/shirt/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMDQ1NywiZXhwIjoxNjQyMjI0MDU3fQ.Xo0Lf4YzN2gCQmdgE3hKU1iEPV2NHD266SEnzX0VLic

{
  "id": 10,
  "name": "saman",
  "height": 220,
  "shoulder": 123,
  "sleeve": 145,
  "sleeveRing": 12,
  "armpit": 64,
  "chest": 77,
  "collar": 23,
  "phone": "09174163042"
}

### list of shirt

GET http://localhost:5000/shirt/list?page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMDQ1NywiZXhwIjoxNjQyMjI0MDU3fQ.Xo0Lf4YzN2gCQmdgE3hKU1iEPV2NHD266SEnzX0VLic

### get details

GET http://localhost:5000/shirt/details?id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MjIyMzAxNSwiZXhwIjoxNjQyMjIzMDc1fQ.BMj63cn8V2HX3ulxeiDQ7KwXxbFCTtEDvZ6NLkOJPc4

